language: node_js
notifications:
  email: false
node_js:
  - "11"
  - "10"
  - "8"
dist: trusty
addons:
  chrome: stable
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
script:
  - nyc --reporter=lcov yarn ci-test
  - yarn build
  - yarn codecov -t $CODECOV_TOKEN
